### ISSUE TITLE
sbds jsonrpc lib: "Attempt to overwrite %r in LogRecord"

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#18]
Saw several of these occurring in dev, not sure what the cause is:

```
Traceback (most recent call last):  
  File "/usr/local/lib/python3.5/dist-packages/bottle.py", line 862, in _handle  
    return route.call(**args)  
  File "/usr/local/lib/python3.5/dist-packages/bottle.py", line 1740, in wrapper  
    rv = callback(*a, **ka)  
  File "/app/hive/sbds/jsonrpc.py", line 64, in rpc  
    self.logger.error('Parse Error, Not JSON', extra=request.body.read())  
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error  
    self._log(ERROR, msg, args, **kwargs)  
  File "/usr/lib/python3.5/logging/__init__.py", line 1414, in _log  
    exc_info, func, extra, sinfo)  
  File "/usr/lib/python3.5/logging/__init__.py", line 1388, in makeRecord  
    raise KeyError("Attempt to overwrite %r in LogRecord" % key)  
KeyError: 'Attempt to overwrite 109 in LogRecord' 
```

```
KeyError: 'Attempt to overwrite 51 in LogRecord'
```

etc

**Comment by roadscape** [comment]
Haven't seen recently, closing.
