### ISSUE TITLE
SQL syntax error in fork recovery if no posts were in that block

### ISSUE THREAD

**Issue by jrawsthorne** [steemit/hivemind#202]
During fork recovery we remove all rows from the hive_posts, hive_posts_cache and hive_post_tags tables that were in the orphaned block. In 

https://github.com/steemit/hivemind/blob/cd78b952b55911b63a59c762d1d4530a25d7d8f5/hive/indexer/blocks.py#L200

https://github.com/steemit/hivemind/blob/cd78b952b55911b63a59c762d1d4530a25d7d8f5/hive/indexer/blocks.py#L204

https://github.com/steemit/hivemind/blob/cd78b952b55911b63a59c762d1d4530a25d7d8f5/hive/indexer/blocks.py#L205

 if there were no posts the id list is empty. This causes the sql statements to be 
```
DELETE FROM hive_posts_cache WHERE post_id IN ()
DELETE FROM hive_post_tags WHERE post_id IN ()
DELETE FROM hive_posts WHERE id IN ()
```
which is invalid. I think a simple fix would be to just check if the length of the list post_ids is greater than zero before deleting from hive_posts, hive_posts_cache and hive_post_tags.

Log showing this issue
```
NOTIFYALERT! hivemindsync quit unexpectedly, restarting hive sync...,
INFO:root:loaded configuration:,
Command Line Args:   sync,
Environment Variables:,
  DATABASE_URL:      ###################,
  STEEMD_URL:        ###################,
  HTTP_SERVER_PORT:  8080,
  MAX_BATCH:         10,
  TRAIL_BLOCKS:      0,
  LOG_LEVEL:         DEBUG,,
:,
  mode:              ['sync'],
  --max-workers:     4,
  --sync-to-s3:      False,
  --test-disable-sync:False,
,
INFO:hive.steem.http_client:using node: https://rpc.usesteem.com,
INFO:hive.db.db_state:[INIT] Welcome to hive!,
INFO:hive.db.db_state:[HIVE] db version: 12,
INFO:hive.db.db_state:[INIT] Hive initialized.,
WARNING:hive.utils.stats:[SQL][856ms] SELECT name, id FROM hive_accounts,
WARNING:hive.utils.stats:[STEEM][264ms] get_block[1] -- 3.8x par (189/50),
INFO:hive.indexer.blocks:[INIT] fork check. block 31882192: 01e67bd0048f065cea5f7158b1fc3ea4b1027ad6 vs 01e67bd00210d9b690c4201336a66c0a0872f9ff --- invalid,
INFO:hive.indexer.blocks:[INIT] fork check. block 31882191: 01e67bcf86a9e597c0a47135716dc396f206b54f vs 01e67bcf86a9e597c0a47135716dc396f206b54f --- ok,
ERROR:hive.indexer.blocks:[FORK] depth is 1; popping blocks 31882192 - 31882192,
WARNING:hive.indexer.blocks:[FORK] popping block 31882192 @ 2019-04-09 02:41:45,
WARNING:hive.utils.stats:[SQL][60629ms] SELECT id FROM hive_posts WHERE created_at >= :date,
INFO:hive.db.adapter:[SQL-ERR] ProgrammingError in query DELETE FROM hive_posts_cache WHERE post_id IN :ids ({'ids': ()}),
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context,
    cursor, statement, parameters, context,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute,
    cursor.execute(statement, parameters),
psycopg2.ProgrammingError: syntax error at or near ")",
LINE 1: DELETE FROM hive_posts_cache WHERE post_id IN (),
                                                       ^,
,
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "/usr/local/bin/hive", line 11, in <module>,
    sys.exit(run()),
  File "/usr/local/lib/python3.6/dist-packages/hive/cli.py", line 24, in run,
    Sync(conf=conf).run(),
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/sync.py", line 52, in run,
    Blocks.verify_head(self._steem),
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/blocks.py", line 141, in verify_head,
    cls._pop(to_pop),
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/blocks.py", line 200, in _pop,
    DB.query("DELETE FROM hive_posts_cache WHERE post_id IN :ids", ids=post_ids),
  File "/usr/local/lib/python3.6/dist-packages/hive/db/adapter.py", line 79, in query,
    return self._query(sql, **kwargs),
  File "/usr/local/lib/python3.6/dist-packages/hive/db/adapter.py", line 182, in _query,
    raise e,
  File "/usr/local/lib/python3.6/dist-packages/hive/db/adapter.py", line 176, in _query,
    result = self._exec(query, **kwargs),
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 974, in execute,
    return meth(self, multiparams, params),
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection,
    return connection._execute_clauseelement(self, multiparams, params),
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement,
    distilled_params,,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context,
    e, statement, parameters, cursor, context,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception,
    util.raise_from_cause(sqlalchemy_exception, exc_info),
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause,
    reraise(type(exception), exception, tb=exc_tb, cause=cause),
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise,
    raise value.with_traceback(tb),
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context,
    cursor, statement, parameters, context,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute,
    cursor.execute(statement, parameters),
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near ")",
LINE 1: DELETE FROM hive_posts_cache WHERE post_id IN (),
                                                       ^,
 [SQL: 'DELETE FROM hive_posts_cache WHERE post_id IN %(ids)s'] [parameters: {'ids': ()}] (Background on this error at: http://sqlalche.me/e/f405),
INFO:hive.utils.stats:cumtime 61s (97.7% of 63s). 0.0% idle. peak 393mb.,
INFO:hive.utils.stats:Service: db -- 61s total (99.4%),
INFO:hive.utils.stats:  -pct-     -ttl-     -avg-     -cnt-,
INFO:hive.utils.stats:  98.6%   60629ms  60629.12        1x -- SELECT id FROM hive_posts WHERE created_at >= :date,
INFO:hive.utils.stats:   1.4%     856ms    856.13        1x -- SELECT name, id FROM hive_accounts,
INFO:hive.utils.stats:   0.0%       2ms      1.44        2x -- SELECT num FROM hive_blocks ORDER BY num DESC LIMIT 1,
INFO:hive.utils.stats:   0.0%       2ms      2.37        1x -- SELECT 1 FROM pg_catalog.pg_tables WHERE schemaname = 'public',
INFO:hive.utils.stats:   0.0%       2ms      1.06        2x -- SELECT num, created_at date, hash FROM hive_blocks WHERE num = :num LIMIT 1,
INFO:hive.utils.stats:   0.0%       1ms      1.09        1x -- SELECT 1 FROM hive_feed_cache LIMIT 1,
INFO:hive.utils.stats:   0.0%       0ms      0.95        1x -- ALTER TABLE hive_accounts SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 50000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 100000),
INFO:hive.utils.stats:   0.0%       0ms      0.71        1x -- START TRANSACTION,
INFO:hive.utils.stats:   0.0%       0ms      0.55        1x -- SELECT db_version FROM hive_state LIMIT 1,
INFO:hive.utils.stats:   0.0%       0ms      0.48        1x -- ALTER TABLE hive_posts SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 2500, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 10000),
INFO:hive.utils.stats:   0.0%       0ms      0.47        1x -- ALTER TABLE hive_posts_cache SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuu ... ld = 25000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 25000),
INFO:hive.utils.stats:   0.0%       0ms      0.43        1x -- ALTER TABLE hive_reblogs SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000),
INFO:hive.utils.stats:   0.0%       0ms      0.40        1x -- ALTER TABLE hive_payments SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000),
INFO:hive.utils.stats:   0.0%       0ms      0.40        1x -- ALTER TABLE hive_blocks SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 25000),
INFO:hive.utils.stats:   0.0%       0ms      0.35        1x -- ALTER TABLE hive_feed_cache SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000),
INFO:hive.utils.stats:   0.0%       0ms      0.35        1x -- ALTER TABLE hive_post_tags SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 10000),
INFO:hive.utils.stats:   0.0%       0ms      0.34        1x -- ALTER TABLE hive_follows SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000),
INFO:hive.utils.stats:Service: steem -- 0s total (0.6%),
INFO:hive.utils.stats:  -pct-     -ttl-     -avg-     -cnt-,
INFO:hive.utils.stats:  86.6%     317ms    158.64        2x -- get_block,
INFO:hive.utils.stats:  13.4%      49ms     49.21        1x -- get_dynamic_global_properties,
```

**Comment by roadscape** [comment]
Thanks for the report! Proposed fix in PR #203
