### ISSUE TITLE
Error:  assert post['active_votes'] or int(post['net_rshares']) == 0

### ISSUE THREAD

**Issue by DoctorLai** [steemit/hivemind#324]
in the docker logs

```INFO:hive.utils.stats:   0.9%      46ms     46.61        1x -- get_order_book
Traceback (most recent call last):
  File "/usr/local/bin/hive", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/hive/cli.py", line 23, in run
    launch_mode(mode, conf)
  File "/usr/local/lib/python3.6/dist-packages/hive/cli.py", line 34, in launch_mode
    Sync(conf=conf).run()
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/sync.py", line 88, in run
    CachedPost.flush(self._steem, trx=True)
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 191, in flush
    cls._update_batch(steem, tuples, trx, full_total=full_total)
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 358, in _update_batch
    buffer.extend(cls._sql(pid, post, level=level))
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 513, in _sql
    payout = post_payout(post)
  File "/usr/local/lib/python3.6/dist-packages/hive/utils/post.py", line 190, in post_payout
    assert post['active_votes'] or int(post['net_rshares']) == 0
AssertionError```

**Comment by ety001** [comment]
no more info
