### ISSUE TITLE
AssertionError in post_payout: Mismatch between active_votes and net_rshares

### ISSUE THREAD

**Issue by BottoStm** [steemit/hivemind#344]
Description:
The post_payout function in Hivemind raises an AssertionError under certain conditions due to a mismatch between the active_votes and net_rshares fields in the post data retrieved from the blockchain.

The specific code causing the error is:

assert post['active_votes'] or int(post['net_rshares']) == 0
This assertion assumes that:

If a post has no active_votes, its net_rshares must be zero.
If this condition is violated, the assertion fails.
 
Steps to Reproduce:
Sync Hivemind with a Steemd node.
Encounter posts with the following conditions:
Non-zero net_rshares.
Empty or missing active_votes.
Observe the error in the logs:

AssertionError: post['active_votes'] or int(post['net_rshares']) == 0

Expected Behavior:
The code should handle such edge cases gracefully by:

Logging a warning about inconsistent data.
Skipping the problematic post or assigning safe defaults.
Actual Behavior:
The process fails entirely due to the AssertionError, interrupting the sync process.

**Comment by BottoStm** [comment]
NOTIFYALERT! hivemindsync quit unexpectedly, restarting hive sync...
INFO:root:loaded configuration:
Command Line Args:   sync
Environment Variables:
  DATABASE_URL:      postgresql://steem:<redacted>@db:5432/hivedb
  STEEMD_URL:        http://10.10.100.12:8080
  REDIS_URL:         redis://hivemind-redis:6379
  HTTP_SERVER_PORT:  8080
  MAX_WORKERS:       8
  MAX_BATCH:         30
  TRAIL_BLOCKS:      2
  LOG_LEVEL:         INFO
Defaults:
  mode:              ['sync']
  --muted-accounts-url:
  --sync-to-s3:      False
  --recommend-communities:hive-108451,hive-172186,hive-187187
  --test-disable-sync:False
  --test-profile:    False
  --txid-collector:  False

INFO:hive.steem.http_client:using node: http://10.10.100.12:8080
INFO:hive.db.db_state:[INIT] Welcome to hive!
INFO:hive.db.db_state:[HIVE] db version: 20
INFO:hive.db.db_state:[INIT] Hive initialized.
WARNING:hive.utils.stats:[SQL][639ms] SELECT name, id FROM hive_accounts
WARNING:hive.utils.stats:[SQL][505ms] SELECT id FROM hive_accounts ORDER BY vote_weight DESC
INFO:hive.indexer.blocks:[INIT] fork check. block 91158381: 056ef76d48b59b27dd453b2c2c01fca3317c4397 vs 056ef76d48b59b27dd453b2c2c01fca3317c4397 --- ok
INFO:hive.indexer.cached_post:[INIT] 982207 missing post cache entries
INFO:hive.indexer.cached_post:[PREP] posts cache process: 250000 inserts
WARNING:hive.steem.http_client:get_content[30] failed in 0.1s. try 1. {'jussi-id': '001067473736941478', 'secs': 0.139, 'try': 1} - RPCError("unspecified exception[-32603]: `Internal Error` [jussi:9fd3502e-30b4-4a2c-baf3-1f3886195793] in condenser_api.get_content([['sayedabdullah', '3jzswm'], (29 more)])",)
INFO:hive.indexer.cached_post:skipped 1 ids 109197843 -> 109197845
INFO:hive.indexer.cached_post:skip 43 mentions in @playdice/20240823044854532-diceroll
INFO:hive.indexer.cached_post:skipped 1 ids 109197998 -> 109198000
INFO:hive.indexer.cached_post:skipped 1 ids 109198012 -> 109198014
INFO:hive.indexer.cached_post:skipped 1 ids 109198125 -> 109198127
INFO:hive.indexer.cached_post:skipped 1 ids 109198218 -> 109198220
INFO:hive.indexer.cached_post:skip 262 mentions in @cnbuddy-reward/20240823t060000318z-post
Traceback (most recent call last):
  File "/usr/local/bin/hive", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/hive/cli.py", line 23, in run
    launch_mode(mode, conf)
  File "/usr/local/lib/python3.6/dist-packages/hive/cli.py", line 34, in launch_mode
    Sync(conf=conf).run()
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/sync.py", line 68, in run
    CachedPost.recover_missing_posts(self._steem)
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 308, in recover_missing_posts
    while cls.flush(steem, trx=True, full_total=gap)['insert']:
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 191, in flush
    cls._update_batch(steem, tuples, trx, full_total=full_total)
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 358, in _update_batch
    buffer.extend(cls._sql(pid, post, level=level))
  File "/usr/local/lib/python3.6/dist-packages/hive/indexer/cached_post.py", line 513, in _sql
    payout = post_payout(post)
  File "/usr/local/lib/python3.6/dist-packages/hive/utils/post.py", line 190, in post_payout
    assert post['active_votes'] or int(post['net_rshares']) == 0
AssertionError
INFO:hive.utils.stats:cumtime 2s (29.8% of 8s). 0.0% idle. peak 890mb.
INFO:hive.utils.stats:Service: db -- 2s total (81.1%)
INFO:hive.utils.stats:  -pct-     -ttl-     -avg-     -cnt-
INFO:hive.utils.stats:  32.5%     639ms    639.96        1x -- SELECT name, id FROM hive_accounts
INFO:hive.utils.stats:  25.7%     505ms    505.71        1x -- SELECT id FROM hive_accounts ORDER BY vote_weight DESC
INFO:hive.utils.stats:  25.4%     499ms      0.17     3002x -- UPDATE hive_communities SET sum_pending = :payouts, num_pending = :posts, num_authors = :authors, rank = :rank WHERE id = :id
INFO:hive.utils.stats:   6.1%     120ms    120.30        1x -- SELECT id, author, permlink, promoted FROM hive_posts WHERE is_deleted = '0' AND id > :id ORDER BY id LIMIT :limit
INFO:hive.utils.stats:   3.9%      76ms      0.18      426x -- SELECT 1 FROM hive_follows WHERE follower = :account AND following = :target AND state IN (2,3)
INFO:hive.utils.stats:   3.7%      72ms      0.17      426x -- INSERT INTO hive_notifs (type_id, score, created_at, src_id, dst_id, post_id, communit ... S (:type_id, :score, :created_at, :src_id, :dst_id, :post_id, :community_id, :payload)
INFO:hive.utils.stats:   1.3%      24ms      0.17      146x -- SELECT 1 FROM hive_notifs WHERE dst_id = :dst_id AND post_id = :post_id AND type_id = 16
INFO:hive.utils.stats:   1.0%      20ms     20.42        1x -- SELECT id, COALESCE(posts, 0), COALESCE(payouts, 0), COALESCE(authors, 0) FROM hive_co ...  COALESCE(posts, 0) DESC, subscribers DESC, (CASE WHEN c.title = '' THEN 1 ELSE 0 END)
INFO:hive.utils.stats:   0.1%       2ms      2.95        1x -- SELECT id, category, community_id, is_muted, is_valid FROM hive_posts WHERE id IN :ids
INFO:hive.utils.stats:   0.1%       1ms      0.29        5x -- SELECT COUNT(*) FROM hive_posts WHERE id BETWEEN :x1 AND :x2 AND is_deleted = '0'
INFO:hive.utils.stats:   0.1%       1ms      1.09        1x -- SELECT 1 FROM pg_catalog.pg_tables WHERE schemaname = 'public'
INFO:hive.utils.stats:   0.0%       0ms      0.58        1x -- SELECT MAX(id) FROM hive_posts WHERE is_deleted = '0'
INFO:hive.utils.stats:   0.0%       0ms      0.53        1x -- SELECT num FROM hive_blocks ORDER BY num DESC LIMIT 1
INFO:hive.utils.stats:   0.0%       0ms      0.45        1x -- SELECT COALESCE(MAX(post_id), 0) FROM hive_posts_cache
INFO:hive.utils.stats:   0.0%       0ms      0.38        1x -- ALTER TABLE hive_accounts SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 50000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 100000)
INFO:hive.utils.stats:   0.0%       0ms      0.33        1x -- SELECT 1 FROM hive_feed_cache LIMIT 1
INFO:hive.utils.stats:   0.0%       0ms      0.31        1x -- SELECT num, created_at date, hash FROM hive_blocks WHERE num = :num LIMIT 1
INFO:hive.utils.stats:   0.0%       0ms      0.29        1x -- SELECT db_version FROM hive_state LIMIT 1
INFO:hive.utils.stats:   0.0%       0ms      0.25        1x -- ALTER TABLE hive_posts_cache SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuu ... ld = 25000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 25000)
INFO:hive.utils.stats:   0.0%       0ms      0.24        1x -- ALTER TABLE hive_posts SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 2500, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 10000)
INFO:hive.utils.stats:   0.0%       0ms      0.19        1x -- ALTER TABLE hive_payments SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000)
INFO:hive.utils.stats:   0.0%       0ms      0.18        1x -- ALTER TABLE hive_follows SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000)
INFO:hive.utils.stats:   0.0%       0ms      0.18        1x -- ALTER TABLE hive_blocks SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 25000)
INFO:hive.utils.stats:   0.0%       0ms      0.18        1x -- ALTER TABLE hive_post_tags SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 10000)
INFO:hive.utils.stats:   0.0%       0ms      0.17        1x -- ALTER TABLE hive_reblogs SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000)
INFO:hive.utils.stats:   0.0%       0ms      0.16        1x -- ALTER TABLE hive_feed_cache SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 5000, autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 5000)
INFO:hive.utils.stats:Service: steem -- 0s total (18.9%)
INFO:hive.utils.stats:  -pct-     -ttl-     -avg-     -cnt-
INFO:hive.utils.stats:  98.9%     452ms      0.45     1000x -- get_content
INFO:hive.utils.stats:   1.1%       4ms      4.86        1x -- get_block

**Comment by BottoStm** [comment]
Proposed Solution:
Replace the assert statement with a conditional check and log inconsistent posts:



if not (post['active_votes'] or int(post['net_rshares']) == 0):
    print(f"Skipping post due to invalid data: {post}")
    return {
        'payout': 0,
        'rshares': 0,
        'csvotes': '',
        'sc_trend': 0,
        'sc_hot': 0
    }
