### ISSUE TITLE
errors w/ api server

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#35]
https://hive.steemitdev.com/health
https://hive.steemitstage.com/health
both return 500

**Comment by roadscape** [comment]
```
$ curl -H 'Content-Type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"db_head_state"}' https://hive.steemitstage.com
{"jsonrpc": "2.0", "error": {"data": "(sqlalchemy.exc.ResourceClosedError) This Connection is closed [SQL: \"SELECT num,created_at,UNIX_TIMESTAMP(CONVERT_TZ(created_at, '+00:00', 'SYSTEM')) ts FROM hive_blocks ORDER BY num DESC LIMIT 1\"]", "message": "Server error", "code": -32000}, "id": 1}
```

**Comment by roadscape** [comment]
The error in the previous comment may be related to this.. it seems like mysql may have crashed, saw this in the logs:
```
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]: ERROR:aiohttp.server:Error handling request
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]: Traceback (most recent call last):
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 416, in start
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]:     resp = yield from self._request_handler(request)
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 323, in _handle
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]:     resp = yield from handler(request)
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]:   File "/app/hive/server/serve.py", line 75, in health
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]:     if state['db_head_age'] > app['config']['hive.MAX_BLOCK_NUM_DIFF'] * 3:
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]: TypeError: 'coroutine' object is not subscriptable
10:26:33.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]: INFO:aiohttp.access:x.x.x.x - - [21/Nov/2017:16:26:33 +0000] "GET /health HTTP/1.1" 500 330 "-" "Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)"
[...]
10:39:54.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]: INFO:jsonrpcserver.dispatcher.request:{"id":1,"jsonrpc":"2.0","method":"db_head_state"}
10:39:54.000 steemit-staging-hivemind-001_i-07715a45ee485c86a /var/log/messages docker/03af14cb0434[24195]: ERROR:hive.db.methods:(_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: "SELECT num,created_at,UNIX_TIMESTAMP(CONVERT_TZ(created_at, '+00:00', 'SYSTEM')) ts FROM hive_blocks ORDER BY num DESC LIMIT 1"]

```

**Comment by roadscape** [comment]
With the last commit, the `/health` endpoint looks good. However, seeing errors with methods which used to work:
```
$ http -j post https://hive.steemitdev.com jsonrpc=2.0 id=1 method=get_user_feed params:='{"account":"roadscape","skip":0,"limit":20}'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 526
Content-Type: application/json; charset=utf-8
Date: Tue, 21 Nov 2017 20:41:00 GMT
Server: Python/3.5 aiohttp/2.3.3

{
    "error": {
        "code": -32000,
        "data": "(_mysql_exceptions.ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3\") [SQL: '\\n    SELECT post_id, author, permlink, title, preview, img_url, payout,\\n           promoted, created_at, payout_at, is_nsfw, rshares, votes, json\\n      FROM hive_posts_cache WHERE post_id IN %s\\n    '] [parameters: ([])]",
        "message": "Server error"
    },
    "id": "1",
    "jsonrpc": "2.0"
}

$ http -j post https://hive.steemitdev.com jsonrpc=2.0 id=1 method=get_user_feed params:='{"account":"roadscape","skip":0,"limit":20,"context":"roadscape"}'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 528
Content-Type: application/json; charset=utf-8
Date: Tue, 21 Nov 2017 20:41:25 GMT
Server: Python/3.5 aiohttp/2.3.3

{
    "error": {
        "code": -32000,
        "data": "(sqlalchemy.exc.ResourceClosedError) This Connection is closed [SQL: '\\n      SELECT post_id, GROUP_CONCAT(account) accounts\\n        FROM hive_feed_cache\\n       WHERE account IN (SELECT following FROM hive_follows\\n                          WHERE follower = %s AND state = 1)\\n    GROUP BY post_id\\n    ORDER BY MIN(created_at) DESC LIMIT %s OFFSET %s\\n    '] [parameters: [{'skip': 0, 'account': 'roadscape', 'limit': 20}]]",
        "message": "Server error"
    },
    "id": "1",
    "jsonrpc": "2.0"
}
```

**Comment by roadscape** [comment]
The very first jsonrpc request I tried on a fresh launch worked:

```
$ http -j post https://hive.steemitdev.com jsonrpc=2.0 id=1 method=db_head_state params:='[]'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 131
Content-Type: application/json; charset=utf-8
Date: Tue, 21 Nov 2017 20:39:02 GMT
Server: Python/3.5 aiohttp/2.3.3

{
    "id": "1",
    "jsonrpc": "2.0",
    "result": {
        "db_head_age": 47395553,
        "db_head_block": 1664000,
        "db_head_time": "2016-05-22 07:13:09"
    }
}
```

But after the aforementioned errors, mysql process seems fouled:

```
$ http -j post https://hive.steemitdev.com jsonrpc=2.0 id=1 method=db_head_state params:='[]'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 295
Content-Type: application/json; charset=utf-8
Date: Tue, 21 Nov 2017 20:45:31 GMT
Server: Python/3.5 aiohttp/2.3.3

{
    "error": {
        "code": -32000,
        "data": "(sqlalchemy.exc.ResourceClosedError) This Connection is closed [SQL: \"SELECT num,created_at,UNIX_TIMESTAMP(CONVERT_TZ(created_at, '+00:00', 'SYSTEM')) ts FROM hive_blocks ORDER BY num DESC LIMIT 1\"]",
        "message": "Server error"
    },
    "id": "1",
    "jsonrpc": "2.0"
}
```
