### ISSUE TITLE
not recovering from string of 502's

### ISSUE THREAD

**Issue by roadscape** [steemit/hivemind#77]
After HttpClient re-org, built-in retries are not robust enough. Need to fix it either in the Client or Adapter.

```
WARNING: ignoring deleted post 29464431
[LIVE] Got block 19553853 at 2018-02-03T18:59:15 --  70 txs, 11 posts, 16 edits,  8 payouts, 22 accounts, 15 follows --  581ms
ERROR:root:call failed, retry 0. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 1. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 2. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 3. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 4. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 5. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 6. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 7. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 8. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 9. RPCInvalidStatus('non-200 response:502',)
ERROR:root:call failed, retry 10. RPCInvalidStatus('non-200 response:502',)
Traceback (most recent call last):
  File "hive/indexer/http_client.py", line 159, in _exec
    raise RPCInvalidStatus("non-200 response:%s" % response.status)
hive.indexer.http_client.RPCInvalidStatus: non-200 response:502

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hive/indexer/http_client.py", line 159, in _exec
    raise RPCInvalidStatus("non-200 response:%s" % response.status)
hive.indexer.http_client.RPCInvalidStatus: non-200 response:502

(+10x)
```

**Comment by inertia186** [comment]
Shot in the dark: maybe you or the upstream ran out of file handles.

```bash
lsof | awk '{ print $2; }' | uniq -c | sort -rn | head
```
